<a href="https://colab.research.google.com/github/AdityaFaisal/DataMining/blob/main/TugasPreprossesing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [157]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [164]:
dataset = pd.read_csv('Tugas.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [165]:
print(x)

[['Kevin' 4.0 720000.0]
 ['Zidan' 2.0 4800000.0]
 ['Serli' 3.0 2400000.0]
 ['Zidan' 3.0 1200000.0]
 ['Serli' 4.0 nan]
 ['Kevin' 3.0 5800000.0]
 ['Zidan' nan 5200000.0]
 ['Kevin' 8.0 1500000.0]
 ['Serli' 5.0 4300000.0]
 ['Kevin' 7.0 2000000.0]]


In [166]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [183]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:4])
x[:, 1:4] = imputer.transform(x[:, 1:4])

In [185]:
print(x)

[[1.0 0.0 0.0 4.0 720000.0]
 [0.0 0.0 1.0 2.0 4800000.0]
 [0.0 1.0 0.0 3.0 2400000.0]
 [0.0 0.0 1.0 3.0 1200000.0]
 [0.0 1.0 0.0 4.0 3102222.222222222]
 [1.0 0.0 0.0 3.0 5800000.0]
 [0.0 0.0 1.0 4.333333333333333 5200000.0]
 [1.0 0.0 0.0 8.0 1500000.0]
 [0.0 1.0 0.0 5.0 4300000.0]
 [1.0 0.0 0.0 7.0 2000000.0]]


In [186]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [187]:
print(x)

[[0.0 1.0 0.0 0.0 4.0 720000.0]
 [1.0 0.0 0.0 1.0 2.0 4800000.0]
 [1.0 0.0 1.0 0.0 3.0 2400000.0]
 [1.0 0.0 0.0 1.0 3.0 1200000.0]
 [1.0 0.0 1.0 0.0 4.0 3102222.222222222]
 [0.0 1.0 0.0 0.0 3.0 5800000.0]
 [1.0 0.0 0.0 1.0 4.333333333333333 5200000.0]
 [0.0 1.0 0.0 0.0 8.0 1500000.0]
 [1.0 0.0 1.0 0.0 5.0 4300000.0]
 [0.0 1.0 0.0 0.0 7.0 2000000.0]]


In [188]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [189]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [190]:
from sklearn.model_selection import train_test_split
x_train, x_text, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=1)

In [191]:
print(x_train)

[[1.0 0.0 1.0 0.0 4.0 3102222.222222222]
 [0.0 1.0 0.0 0.0 4.0 720000.0]
 [1.0 0.0 0.0 1.0 3.0 1200000.0]
 [1.0 0.0 0.0 1.0 2.0 4800000.0]
 [0.0 1.0 0.0 0.0 8.0 1500000.0]
 [1.0 0.0 1.0 0.0 5.0 4300000.0]
 [0.0 1.0 0.0 0.0 3.0 5800000.0]]


In [192]:
print (y_test)

[0 1 0]


In [193]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 5:] =sc.fit_transform(x_train[:, 5:])
x_text[:, 5:] =sc.transform(x_text[:, 5:])

In [194]:
print(x_text)

[[1.0 0.0 1.0 0.0 3.0 -0.36082088630000125]
 [0.0 1.0 0.0 0.0 7.0 -0.579395077039425]
 [1.0 0.0 0.0 1.0 4.333333333333333 1.1691984488759655]]
